# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

environment:
  PSGalleryApiKey:
    secure: LwSHxTwnDG7eUFOPZSAfy5Wj0Zi5hUc7CB290hC3DcnmVkvK5y76h6miZJUJCBBw

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1 -Task Test
